project_id = "cfjcuhblioswylmtclzy"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.import-schools]
verify_jwt = false

[functions.sync-calendar]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.newsletter-checker]
verify_jwt = false