// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-children.ts
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function userClient(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_children_default = defineTool({
  name: "list_children",
  title: "List children",
  description: "List the signed-in parent's children (name, year group, school).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = userClient(ctx);
    const { data, error } = await supabase.from("children").select("id, first_name, year_group, school_id").order("first_name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { children: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.96.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function userClient2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_default = defineTool2({
  name: "list_upcoming_notes",
  title: "List upcoming saved notes",
  description: "List the signed-in parent's upcoming parent notes (forwarded messages / school letters) within the next N days.",
  inputSchema: {
    days: z.number().int().min(1).max(60).default(7).describe("Look-ahead window in days (default 7).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = userClient2(ctx);
    const { data, error } = await supabase.rpc("get_upcoming_parent_notes", {
      _user_id: ctx.getUserId(),
      _days: days ?? 7
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recurring-reminders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.96.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function userClient3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recurring_reminders_default = defineTool3({
  name: "list_recurring_reminders",
  title: "List recurring reminders",
  description: "List active weekly child reminders (e.g. PE kit, swimming) for the signed-in parent's children.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = userClient3(ctx);
    const { data, error } = await supabase.from("child_reminders").select("id, title, day_of_week, emoji, active, child_id, children(first_name)").eq("active", true).order("day_of_week");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { reminders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cfjcuhblioswylmtclzy";
var mcp_default = defineMcp({
  name: "monty-mcp",
  title: "Monty",
  version: "0.1.0",
  instructions: "Tools for Monty, the WhatsApp assistant for UK primary-school parents. Use list_children to see the signed-in parent's children, list_upcoming_notes for saved reminders from forwarded school messages, and list_recurring_reminders for weekly things like PE kit or swimming.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_children_default, list_upcoming_default, list_recurring_reminders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
